### ISSUE TITLE
Missing Font?

### ISSUE THREAD

**Issue by ianm32** [LorduFreeman/foundry-lordudice#2]
When I'm looking through the console, it seems that there is a font missing from the module which is causing an error.  I don't notice any effect on the overall functionality, but it seemed like it might be worth mentioning.
![10](https://user-images.githubusercontent.com/27756065/149444054-c134aafe-f0e2-409f-b465-da9604f67473.JPG)

**Comment by LorduFreeman** [comment]
When are you getting the error message? You are correct, it's a minor oversight - I'm importing a font (Halant) but it's not used by any of my dice configurations thus it is not selectable. I need to check whether I'll delete the import entry or properly embed the font in the module.

**Comment by ianm32** [comment]
Hi,

I shared reports of this with other devs and it sounds like there's a bug in how DsN and Custom Fonts interact with each other, which happens to affect your module as well.  I see the errors and warnings in the console when Foundry is first loading.

**Comment by LorduFreeman** [comment]
I think I fixed this.
