### ISSUE TITLE
Compatibility warning: not verified for v10

### ISSUE THREAD

**Issue by yjeroen** [LorduFreeman/foundry-lordudice#5]
![image](https://user-images.githubusercontent.com/1303988/200176046-add0d3f6-5ae9-4ab0-8f05-3372d67deb07.png)

Would be great if the module.json could be updated if the module is compatible with Foundry V10.

**Comment by LorduFreeman** [comment]
I wanted to add something more than just the compatibility raise to this module but oh well, time. Updated to v10.
