### ISSUE TITLE
Fonts not showing up in The Forge

### ISSUE THREAD

**Issue by JustinB555** [LorduFreeman/foundry-lordudice#6]
Recently switched to using The Forge for a more stable connection and realized that the fonts were not showing up.
![image](https://user-images.githubusercontent.com/60529781/222651371-f99da41e-0def-49c4-a819-3681db3ada86.png)
As you can see here, I have the module installed because I can use Dark Ooze, but none of the fonts are showing up for me. I don't see any error messages related to the fonts either.

I did use Foundry V10's "Additional Fonts" setting to add the font (because the fonts are there, just not being loaded in). I hope that there would be a way that the fonts are added in without having to use an additional step.

Foundry Version: v10.291
System Version: DnD5e - Fifth Edition System v2.1.5
Lordu's Custom Dice Version: 0.35

**Comment by LorduFreeman** [comment]
Confirmed, the fonts need to be loaded in a different way for V10, I need to change my module to enable auto loading again. Not sure when I'll get around to patch this but I will.

**Comment by LorduFreeman** [comment]
Fixed with Version 0.36 (I hope, cannot test on Forge)!
